<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Broadcaster - multiple UDP stream creation"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="1.703">
  <properties />
            <testcase name="broadcasterMultipleUdpCreation" time="1.703" classname="com.zixi.load.testing.BroadcasterMultipleUdpTest">
                <failure type="java.util.concurrent.ExecutionException"
                  message="java.lang.NullPointerException"
              >
<![CDATA[java.util.concurrent.ExecutionException: java.lang.NullPointerException
  java.util.concurrent.FutureTask.report(Unknown Source)
  java.util.concurrent.FutureTask.get(Unknown Source)
  com.zixi.threads.ZthreadPool.zexecuteUdp(ZthreadPool.java:311)
  com.zixi.load.drivers.BroadcasterMultipleUdpDriver.testIMPL(BroadcasterMultipleUdpDriver.java:19)
  com.zixi.load.testing.BroadcasterMultipleUdpTest.broadcasterMultipleUdpCreation(BroadcasterMultipleUdpTest.java:55)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:771)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
  org.testng.TestNG.run(TestNG.java:1032)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
  org.apache.maven.surefire.Surefire.run(Surefire.java:180)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
  org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
Caused by: java.lang.NullPointerException
  com.zixi.drivers.drivers.BroadcasterUdpOutputCreationDriver.testIMPL(BroadcasterUdpOutputCreationDriver.java:21)
  com.zixi.threads.ZthreadPool$4.call(ZthreadPool.java:270)
  com.zixi.threads.ZthreadPool$4.call(ZthreadPool.java:1)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
